app-name: roster
initials: mv
language: gradle

github-app-repo-uri: "git@github.com:mvesper20/roster.git"

github-pipelines-repo-uri: "git@github.com:mvesper20/training-pipelines.git"

cf-dev-api: https://api.run.pivotal.io
cf-dev-org: rscale-training-1
cf-dev-space: miles
cf-dev-hostname: roster-mvesper
cf-dev-domain: cfapps.io
cf-dev-manifest: roster_manifest.yml
